## Dwi Ageng Rohmatullah

## 2009106005

## POSTTEST 5

In [31]:
import pandas as pd
import numpy as np
import sklearn as sk
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

## Classification

### Algoritma KNN

In [32]:
df = pd.read_csv("prepro_ford.csv")
df.head(10)

,Unnamed: 0,year,price,transmission,mileage,fuelType,tax,mpg,engineSize,model_ B-MAX,...,model_ Mondeo,model_ Mustang,model_ Puma,model_ Ranger,model_ S-MAX,model_ Streetka,model_ Tourneo Connect,model_ Tourneo Custom,model_ Transit Tourneo,model_Focus
0,0,2017,12000,0,15944,4.0,150,57.7,1.0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,2018,14000,1,9083,4.0,150,57.7,1.0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,2017,13000,1,12456,4.0,150,57.7,1.0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,2019,17500,1,10460,4.0,145,40.3,1.5,0,...,0,0,0,0,0,0,0,0,0,0
4,4,2019,16500,0,1482,4.0,145,48.7,1.0,0,...,0,0,0,0,0,0,0,0,0,0
5,5,2015,10500,1,35432,4.0,145,47.9,1.6,0,...,0,0,0,0,0,0,0,0,0,0
6,6,2019,22500,1,2029,4.0,145,50.4,1.0,0,...,0,0,1,0,0,0,0,0,0,0
7,7,2017,9000,1,13054,4.0,145,54.3,1.2,0,...,0,0,0,0,0,0,0,0,0,0
8,8,2019,25500,0,6894,0.0,145,42.2,2.0,0,...,0,0,0,0,0,0,0,0,0,0
9,9,2018,10000,1,48141,4.0,145,61.4,1.0,0,...,0,0,0,0,0,0,0,0,0,0

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16737 entries, 0 to 16736
Data columns (total 33 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Unnamed: 0                    16737 non-null  int64
 1   year                          16737 non-null  int64
 2   price                         16737 non-null  int64
 3   transmission                  16737 non-null  int64
 4   mileage                       16737 non-null  int64
 5   fuelType                      16737 non-null  float64
 6   tax                           16737 non-null  int64
 7   mpg                           16737 non-null  float64
 8   engineSize                    16737 non-null  float64
 9   model_ B-MAX                  16737 non-null  int64
 10  model_ C-MAX                  16737 non-null  int64
 11  model_ EcoSport               16737 non-null  int64
 12  model_ Edge                   16737 non-null  int64
 13  model_ Escort                 16737 non-null  int64
 14  model_ Fiesta                 16737 non-null  int64
 15  model_ Focus                  16737 non-null  int64
 16  model_ Fusion                 16737 non-null  int64
 17  model_ Galaxy                 16737 non-null  int64
 18  model_ Grand C-MAX            16737 non-null  int64
 19  model_ Grand Tourneo Connect  16737 non-null  int64
 20  model_ KA                     16737 non-null  int64
 21  model_ Ka+                    16737 non-null  int64
 22  model_ Kuga                   16737 non-null  int64
 23  model_ Mondeo                 16737 non-null  int64
 24  model_ Mustang                16737 non-null  int64
 25  model_ Puma                   16737 non-null  int64
 26  model_ Ranger                 16737 non-null  int64
 27  model_ S-MAX                  16737 non-null  int64
 28  model_ Streetka               16737 non-null  int64
 29  model_ Tourneo Connect        16737 non-null  int64
 30  model_ Tourneo Custom         16737 non-null  int64
 31  model_ Transit Tourneo        16737 non-null  int64
 32  model_Focus                   16737 non-null  int64
dtypes: float64(3), int64(30)
memory usage: 4.2 MB

In [34]:
df = df.drop('Unnamed: 0', axis=1)
df.head()

,year,price,transmission,mileage,fuelType,tax,mpg,engineSize,model_ B-MAX,model_ C-MAX,...,model_ Mondeo,model_ Mustang,model_ Puma,model_ Ranger,model_ S-MAX,model_ Streetka,model_ Tourneo Connect,model_ Tourneo Custom,model_ Transit Tourneo,model_Focus
0,2017,12000,0,15944,4.0,150,57.7,1.0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2018,14000,1,9083,4.0,150,57.7,1.0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2017,13000,1,12456,4.0,150,57.7,1.0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2019,17500,1,10460,4.0,145,40.3,1.5,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2019,16500,0,1482,4.0,145,48.7,1.0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [35]:
x = df.drop('transmission', axis=1)
y = df['transmission']

In [36]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 12)

In [37]:
model = KNeighborsClassifier()

model.fit(x_train, y_train)

KNeighborsClassifier()

In [38]:
y_pred = model.predict(x_test)

In [39]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.32      0.06      0.11       394
           1       0.93      0.99      0.96      4628

    accuracy                           0.92      5022
   macro avg       0.62      0.53      0.53      5022
weighted avg       0.88      0.92      0.89      5022

#### Hasil Supervised Learning Algoritma KNN (K-Nearest Neighbour)

In [40]:
model.score(x_test, y_test)

0.9159697331740343

### Algoritma Naive Bayes

In [41]:
data = pd.read_csv("prepro_ford.csv")
data.head(10)

,Unnamed: 0,year,price,transmission,mileage,fuelType,tax,mpg,engineSize,model_ B-MAX,...,model_ Mondeo,model_ Mustang,model_ Puma,model_ Ranger,model_ S-MAX,model_ Streetka,model_ Tourneo Connect,model_ Tourneo Custom,model_ Transit Tourneo,model_Focus
0,0,2017,12000,0,15944,4.0,150,57.7,1.0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,2018,14000,1,9083,4.0,150,57.7,1.0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,2017,13000,1,12456,4.0,150,57.7,1.0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,2019,17500,1,10460,4.0,145,40.3,1.5,0,...,0,0,0,0,0,0,0,0,0,0
4,4,2019,16500,0,1482,4.0,145,48.7,1.0,0,...,0,0,0,0,0,0,0,0,0,0
5,5,2015,10500,1,35432,4.0,145,47.9,1.6,0,...,0,0,0,0,0,0,0,0,0,0
6,6,2019,22500,1,2029,4.0,145,50.4,1.0,0,...,0,0,1,0,0,0,0,0,0,0
7,7,2017,9000,1,13054,4.0,145,54.3,1.2,0,...,0,0,0,0,0,0,0,0,0,0
8,8,2019,25500,0,6894,0.0,145,42.2,2.0,0,...,0,0,0,0,0,0,0,0,0,0
9,9,2018,10000,1,48141,4.0,145,61.4,1.0,0,...,0,0,0,0,0,0,0,0,0,0

In [43]:
data = data.drop('Unnamed: 0', axis=1)
df.head()

,year,price,transmission,mileage,fuelType,tax,mpg,engineSize,model_ B-MAX,model_ C-MAX,...,model_ Mondeo,model_ Mustang,model_ Puma,model_ Ranger,model_ S-MAX,model_ Streetka,model_ Tourneo Connect,model_ Tourneo Custom,model_ Transit Tourneo,model_Focus
0,2017,12000,0,15944,4.0,150,57.7,1.0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2018,14000,1,9083,4.0,150,57.7,1.0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2017,13000,1,12456,4.0,150,57.7,1.0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2019,17500,1,10460,4.0,145,40.3,1.5,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2019,16500,0,1482,4.0,145,48.7,1.0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [44]:
x = data.drop('transmission', axis=1)
y = data['transmission']

In [49]:
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

In [50]:
gnb = GaussianNB()
gnb.fit(x_train, y_train)

GaussianNB()

In [51]:
y_pred = gnb.predict(x_test)

In [52]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.27      0.24      0.26       394
           1       0.94      0.94      0.94      4628

    accuracy                           0.89      5022
   macro avg       0.60      0.59      0.60      5022
weighted avg       0.88      0.89      0.89      5022

#### Hasil Supervised Learning Algoritma Naive Bayes

In [54]:
akurasi = metrics.accuracy_score(y_test, y_pred) * 100

print("Tingkat akurasi Menggunakan Gaussian NB : ", akurasi, "%")

Tingkat akurasi Menggunakan Gaussian NB :  88.92871365989646 %